// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Alarm
    {

        [JsonProperty("level")]
        public string Level { get; set; }

        [JsonProperty("stat")]
        public string Stat { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("txt")]
        public string Txt { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }
    }

}
