// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Astro
    {

        [JsonProperty("sr")]
        public string Sr { get; set; }

        [JsonProperty("ss")]
        public string Ss { get; set; }
    }

}
