// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class City
    {

        [JsonProperty("aqi")]
        public string Aqi { get; set; }

        [JsonProperty("co")]
        public string Co { get; set; }

        [JsonProperty("no2")]
        public string No2 { get; set; }

        [JsonProperty("o3")]
        public string O3 { get; set; }

        [JsonProperty("pm10")]
        public string Pm10 { get; set; }

        [JsonProperty("pm25")]
        public string Pm25 { get; set; }

        [JsonProperty("qlty")]
        public string Qlty { get; set; }

        [JsonProperty("so2")]
        public string So2 { get; set; }
    }

}
