// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Cond2
    {

        [JsonProperty("code_d")]
        public string CodeD { get; set; }

        [JsonProperty("code_n")]
        public string CodeN { get; set; }

        [JsonProperty("txt_d")]
        public string TxtD { get; set; }

        [JsonProperty("txt_n")]
        public string TxtN { get; set; }
    }

}
