// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class HourlyForecast
    {

        [JsonProperty("date")]
        public string Date { get; set; }

        [JsonProperty("hum")]
        public string Hum { get; set; }

        [JsonProperty("pop")]
        public string Pop { get; set; }

        [JsonProperty("pres")]
        public string Pres { get; set; }

        [JsonProperty("tmp")]
        public string Tmp { get; set; }

        [JsonProperty("wind")]
        public Wind3 Wind { get; set; }
    }

}
