// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Suggestion
    {

        [JsonProperty("comf")]
        public Comf Comf { get; set; }

        [JsonProperty("cw")]
        public Cw Cw { get; set; }

        [JsonProperty("drsg")]
        public Drsg Drsg { get; set; }

        [JsonProperty("flu")]
        public Flu Flu { get; set; }

        [JsonProperty("sport")]
        public Sport Sport { get; set; }

        [JsonProperty("trav")]
        public Trav Trav { get; set; }

        [JsonProperty("uv")]
        public Uv Uv { get; set; }
    }

}
