// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Update
    {

        [JsonProperty("loc")]
        public string Loc { get; set; }

        [JsonProperty("utc")]
        public string Utc { get; set; }
    }

}
