// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Uv
    {

        [JsonProperty("brf")]
        public string Brf { get; set; }

        [JsonProperty("txt")]
        public string Txt { get; set; }
    }

}
