// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class WetherData
    {

        [JsonProperty("basic")]
        public Basic Basic { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("aqi")]
        public Aqi Aqi { get; set; }

        [JsonProperty("alarms")]
        public Alarm[] Alarms { get; set; }

        [JsonProperty("now")]
        public Now Now { get; set; }

        [JsonProperty("daily_forecast")]
        public DailyForecast[] DailyForecast { get; set; }

        [JsonProperty("hourly_forecast")]
        public HourlyForecast[] HourlyForecast { get; set; }

        [JsonProperty("suggestion")]
        public Suggestion Suggestion { get; set; }
    }

}
