// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace EvilLight.Model.Entity
{

    public class Wind2
    {

        [JsonProperty("deg")]
        public string Deg { get; set; }

        [JsonProperty("dir")]
        public string Dir { get; set; }

        [JsonProperty("sc")]
        public string Sc { get; set; }

        [JsonProperty("spd")]
        public string Spd { get; set; }
    }

}
